# The address of your sync server
#sync_address = "https://api.atuin.sh" # Or your own server, e.g., https://atuin.example.com

# Enable/disable auto-sync
auto_sync = false

# Frequency of sync in minutes
#sync_frequency = "5m"

# Style of the UI: 'full' or 'compact'
style = "compact"

# Search mode: 'prefix', 'fuzzy', or 'substring'
search_mode = "fuzzy"

# Filter mode: 'global' (all history), 'host' (this machine), 'directory' (cwd)
filter_mode = "global"

# Whether to show the command directly for editing upon selection
enter_accept = true

# Height of the search window
inline_height = 10

# Disable/Enable usage stats
show_stats = true

[theme]
name = "marine"
